### ISSUE TITLE
Adicionar ao F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [TheFakeMontyOnTheRun/knightsofalentejo#2]
Seria muito bacana ter esse app no F-Droid, que é uma espécie de Google Play mas com apenas software livre: https://f-droid.org/

Aqui tem instruções de como adicioná-lo à fila de inclusão: https://f-droid.org/contribute/

**Comment by TheFakeMontyOnTheRun** [comment]
Conheço e aprecio o f-droid. Confesso nunca ter considerado a possibilidade. Vou olhar com carinho

**Comment by pizzamaker** [comment]
Fantástico :)

**Comment by TheFakeMontyOnTheRun** [comment]
Não consigo fazer meu projeto buildar pelo "fdroid build" - ele cisma em não encontrar minha versão de gradle, mesmo que eu esteja forçando pro diretório de instação do meus wrappers. Acho que esse release vai ter que esperar a plataforma amadurecer um pouco (o que é estranho, uma vez que conheço o F-Droid já tem bastante tempo).

**Comment by pizzamaker** [comment]
Qualquer coisa, pinga o @krt16s que é do próprio F-Droid.

**Comment by TheFakeMontyOnTheRun** [comment]
Ele tentou me ajudar via IRC outro dia, mas estou bastante enrolado atualmente (mudando de emprego, de cidade, de país). Logo que der, volto pra isso.

**Comment by ghost** [comment]
Building looks straight forward to me, at least if any natives libs are re-created at buildtime (which it looks like atm).

@TheFakeMontyOnTheRun If you already have a metadata file, working or not, just post it and I will have a look at it.

**Comment by TheFakeMontyOnTheRun** [comment]
Thanks for your help the other day. As I was saying to @pizzamaker, I'm incredibly busy these days, since I'm not only changing jobs but also moving to another country. Let me know if is there anything else that could help getting the game into F-Droid, pelase.

[br.odb.knights.txt](https://github.com/TheFakeMontyOnTheRun/knightsofalentejo/files/511991/br.odb.knights.txt)

(Hooray, the F-Droid version will be better than the Google Play version!)

**Comment by pizzamaker** [comment]
> (Hooray, the F-Droid version will be better than the Google Play version!)

How so?

**Comment by TheFakeMontyOnTheRun** [comment]
After releasing the Play version, I began working on adding some animations into the game. Eventually this morphed into a completely new game (https://pbs.twimg.com/media/Csp079PWIAEMST2.jpg), but a lot of the effort still remains in this base code.  Even that effort is somewhat stuck in development hell right now; but what remains is a improved version when compared to the Play version.

I will eventually come back to it and revamp it, killing most of the Java code.

**Comment by ghost** [comment]
What dependencies are needed at buildtime? Which NDK was used? Building results in:

```
:app:compileNdkGlueArm64-v8aReleaseAllSharedLibraryNdkGlueArm64-v8aReleaseAllSharedLibraryMainCpp/home/krt/src/fdroiddata/build/br.odb.knights/KnightsOfAlentejoAndroid-AS/app/src/main/jni/GLES2Renderer.cpp:9:10: fatal error: 'glm/glm.hpp' file not found
#include "glm/glm.hpp"
         ^
1 error generated.

/home/krt/src/fdroiddata/build/br.odb.knights/KnightsOfAlentejoAndroid-AS/app/src/main/jni/NdkGlue.cpp:36:10: fatal error: 'glm/glm.hpp' file not found
#include <glm/glm.hpp>
         ^
1 error generated.

/home/krt/src/fdroiddata/build/br.odb.knights/KnightsOfAlentejoAndroid-AS/app/src/main/jni/LightningStrategy.cpp:23:10: fatal error: 'glm/glm.hpp' file not found
#include <glm/glm.hpp>
         ^
1 error generated.

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileNdkGlueArm64-v8aReleaseAllSharedLibraryNdkGlueArm64-v8aReleaseAllSharedLibraryMainCpp'.
> Multiple build operations failed.
      C++ compiler failed while compiling GLES2Renderer.cpp.
      C++ compiler failed while compiling NdkGlue.cpp.
      C++ compiler failed while compiling LightningStrategy.cpp.
```

edit: forget to pull in submodules -.-

**Comment by ghost** [comment]
Builds now, needs some testing first, but should be doable ~~this weekend~~ right now.

Done: https://gitlab.com/fdroid/fdroiddata/commit/170045fd3ad717905d267a8788dfbe79a7932c38

**Comment by TheFakeMontyOnTheRun** [comment]
Thanks man! You're awesome!
